### ISSUE TITLE
Feature request, API methods

### ISSUE THREAD

**Issue by Mottoweb** [danielepiccone/ng-pageslide#90] opened 2016-01-04 18:10 UTC
Would be great to have an exposed API methods for the directive functions.
Like open, close and the rest of the options, as well as the ability to provide templateURL or a string.

**Comment by dpiccone** [comment] 2016-01-07 15:14
This is a duplicate of https://github.com/dpiccone/ng-pageslide/issues/82

**Comment by dpiccone** [comment] 2016-06-06 07:24
How do you mean? 

You can already toggle the pageslide on/off with ps-open within its scope.
Having a template won't be covered by this directive, you can put whatever you want within it by wrapping the template inside the pageslide tags

**Closed** 2018-03-28 13:29 UTC
Labels: enhancement
